const uploads = [
    {title: "Mouse Jiggler", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Auto Login", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Payroll Program", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Time Sheet Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Chat App", combatability: "WIN, MAC, LIN", type: "JavaScript App", walkthrough: "here"},
    {title: "Zoom", combatability: "WIN, MAC, LIN", type: "Program", walkthrough: "here"},
    {title: "Activity Tracker", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Web Scraper", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Selenium Library", combatability: "WIN, MAC, LIN", type: "Selenium Script Library", walkthrough: "here"},
    {title: "Java Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "API Library", combatability: "WIN, MAC, LIN", type: "Library", walkthrough: "here"},
    {title: "Inactivity Solution", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Mouse Jiggler", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Auto Login", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Payroll Program", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Time Sheet Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Chat App", combatability: "WIN, MAC, LIN", type: "JavaScript App", walkthrough: "here"},
    {title: "Zoom", combatability: "WIN, MAC, LIN", type: "Program", walkthrough: "here"},
    {title: "Activity Tracker", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Web Scraper", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Selenium Library", combatability: "WIN, MAC, LIN", type: "Selenium Script Library", walkthrough: "here"},
    {title: "Java Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "API Library", combatability: "WIN, MAC, LIN", type: "Library", walkthrough: "here"},
    {title: "Inactivity Solution", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Mouse Jiggler", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Auto Login", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Payroll Program", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Time Sheet Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "Chat App", combatability: "WIN, MAC, LIN", type: "JavaScript App", walkthrough: "here"},
    {title: "Zoom", combatability: "WIN, MAC, LIN", type: "Program", walkthrough: "here"},
    {title: "Activity Tracker", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Web Scraper", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
    {title: "Selenium Library", combatability: "WIN, MAC, LIN", type: "Selenium Script Library", walkthrough: "here"},
    {title: "Java Auto", combatability: "WIN, MAC, LIN", type: "Selenium Script", walkthrough: "here"},
    {title: "API Library", combatability: "WIN, MAC, LIN", type: "Library", walkthrough: "here"},
    {title: "Inactivity Solution", combatability: "WIN, MAC, LIN", type: "Python Script", walkthrough: "here"},
]
//add alot more fake data

export {uploads}